name: Build-Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debug:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - run: dotnet tool restore
      - run: dotnet build -c Debug -p:DefineConstants=RUNNING_IN_CI
      - run: dotnet build -c Release -p:DefineConstants=RUNNING_IN_CI
      - run: dotnet pack ./src/Multicaster/Multicaster.csproj -c Debug --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - run: dotnet retest -- -c Debug --no-build
      - run: dotnet retest -- -c Release --no-build
      - uses: Cysharp/Actions/.github/actions/upload-artifact@main
        with:
          name: nuget
          path: ./src/Multicaster/bin/Debug/*.*nupkg
          retention-days: 1

  test-release-build:
    name: Run tests using Release build
    needs: [ build-debug ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - run: dotnet build -c Release -p:DefineConstants=RUNNING_IN_CI
      - run: dotnet test -c Release --no-build
